name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  # .NET build and test for RoomServer solution
  dotnet:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: server-dotnet } }
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('server-dotnet/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
        continue-on-error: true # Some tests are currently failing - tracked separately
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: server-dotnet/**/TestResults/*.trx

  # Node/TypeScript build for apps and tools
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install root dependencies
        run: npm install
      - name: Install integration-api dependencies
        run: cd tools/integration-api && npm install
      - name: Install dashboard dependencies
        run: cd apps/operator-dashboard && npm install
      - name: Build integration-api
        run: npm run build:api
      - name: Type check
        run: npm run typecheck

  # JSON Schema and OpenAPI validation
  schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Validate JSON Schemas
        run: cd schemas && npm install && npm run validate
      - name: Validate OpenAPI spec
        run: npx spectral lint configs/schemas/integration-api.openapi.yaml

  # TypeScript MCP servers build
  mcp-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd mcp-ts && pnpm i
      - name: Build all MCP servers
        run: cd mcp-ts && pnpm -r -F "*" build

  # Observability - SSE stream smoke test (experimental)
  observability:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd tools/integration-api && npm install
      - name: Build integration-api
        run: cd tools/integration-api && npm run build
      - name: Start integration-api in background
        run: |
          cd tools/integration-api
          timeout 120 npm start &
          sleep 10
      - name: Run SSE smoke test
        run: node scripts/smoke-stream-test.mjs
        continue-on-error: true

  # Pre-commit checks validation
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install integration-api dependencies
        run: cd tools/integration-api && npm install
      - name: Install schemas dependencies
        run: cd schemas && npm install
      - name: Run format check
        run: npm run format
        continue-on-error: true # Pre-existing format issues in ui/ directory
      - name: Run smoke tests
        run: npm run test:smoke

  # Security audits
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: npm install
      - name: Restore .NET dependencies
        run: cd server-dotnet && dotnet restore
      - name: Run security audit
        run: npm run security:audit
        continue-on-error: true
      - name: Upload security report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: .artifacts/security/

  # Release version validation (dry-run)
  release-dry:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Test release (dry-run)
        run: npm run release:dry

  # E2E tests (requires services)
  e2e:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install integration-api dependencies
        run: cd tools/integration-api && npm install
      - name: Install schemas dependencies
        run: cd schemas && npm install
      - name: Build integration-api
        run: cd tools/integration-api && npm run build
      - name: Start integration-api
        run: |
          cd tools/integration-api
          timeout 120 npm start &
          sleep 15
          # Verify service is responding
          curl -f http://localhost:40901/health || echo "Warning: Health check failed"
      - name: Run E2E tests
        run: npm run test:e2e

  # Documentation validation
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check for broken links (basic)
        run: |
          echo "Checking for basic markdown issues..."
          find docs -name "*.md" -type f -exec grep -l "]()" {} \; || echo "No broken links found"
      - name: Validate docs manifest
        run: |
          if [ -f "docs/docs.manifest.json" ]; then
            node -e "JSON.parse(require('fs').readFileSync('docs/docs.manifest.json'))" && echo "✅ Manifest valid"
          fi
