name: pr-validation
on: pull_request

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - run: dotnet format server-dotnet/RoomServer.sln --verify-no-changes --severity error || (echo "::error::Run 'dotnet format server-dotnet/RoomServer.sln'" && exit 1)
